#pragma once
#include "CoreMinimal.h"
#include "SMVisualEffects.h"
#include "GameFramework/HUD.h"
#include "SMHUD.generated.h"
class UTexture2D;
class USoundWaveProcedural;
class UAudioComponent;
class UMaterialInstanceDynamic;
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FSMDialogueClosed, bool, Completed);
UCLASS()
class ASMHUD : public AHUD {
    GENERATED_BODY()
public:
    ASMHUD();
    virtual void BeginPlay() override;
    virtual void Tick(float DeltaSeconds) override;
    virtual void DrawHUD() override;
    virtual void EndPlay(const EEndPlayReason::Type Reason) override;
    UFUNCTION(BlueprintCallable, Category="Story|Dialogue")
    bool ShowDialogue(const FString& Text, UTexture2D* Portrait = nullptr);
    UFUNCTION(BlueprintCallable, Category="Story|Dialogue")
    void CloseDialogue();
    UFUNCTION(BlueprintPure, Category="Story|Dialogue")
    bool IsDialogueOpen() const;
    UPROPERTY(BlueprintAssignable, Category="Story|Dialogue")
    FSMDialogueClosed OnDialogueClosed;
private:
    void AdvanceSuitTransformation(float Dt);
    void DrawSuitTransformation(float X,float Y,float Scale);
    bool PrepareSuitCapture();
    void CaptureSuitFrame();
    UPROPERTY() TObjectPtr<UTexture2D> SuitGlow;
    int SuitKind=0,SuitPhase=0,SuitRoom=0,SuitTest=0,SuitCaptureFrame=0;
    float SuitTime=0,SuitReleaseTime=-1,SuitFade=0;
    FVector2D SuitPosition=FVector2D::ZeroVector;
    TArray<uint8> SuitCaptureAudio;
    FString SuitCapturePath;
    bool TickDialogue(float Dt);
    void DrawDialogue(float X,float Y,float Scale);
    void FinishDialogue(bool Completed);
    UPROPERTY() TObjectPtr<UTexture2D> DialogueTexture;
    UPROPERTY() TObjectPtr<UTexture2D> DialoguePortrait;
    bool DialogueVisible=false,DialogueInputFence=false;
    int DialogueWidth=400;
    int (*DialogueOpen)(const char*,int)=nullptr;
    void (*DialogueTick)(float,int)=nullptr;
    void (*DialogueClose)()=nullptr;
    int (*DialogueState)(int)=nullptr;
    const uint8* (*DialoguePixels)()=nullptr;
    void ApplyRomWindowIcon();
    void ReleaseRomWindowIcon();
    void* RomWindowIcon=nullptr;
    void* RomIconWindow=nullptr;
    void* PreviousLargeIcon=nullptr;
    void* PreviousSmallIcon=nullptr;
    UPROPERTY() TMap<FName,TObjectPtr<UTexture2D>> TitleTextures;
    UPROPERTY() TObjectPtr<UTexture2D> TitleGlow;
    UPROPERTY() TObjectPtr<UTexture2D> TitleVignette;
    UPROPERTY() TObjectPtr<UTexture2D> TitleFont;
    UPROPERTY() TObjectPtr<UTexture2D> TitleYearFont;
    UPROPERTY() TObjectPtr<class UFont> TitleUiFont;
    UFont* GetTitleUiFont();
    TMap<FName,FVector4f> TitleCrops;
    bool TitleAssetsReady=false,TitleInputFence=false,WarningNeedsRelease=true;
    int StartupWarning=-1,TitlePhase=0,TitlePhaseFrame=0,TitleOpeningFrame=0,TitleLastFrame=-1,TitleLastState=-1;
    float WarningSeconds=0;
    void LoadTitlePresentation();
    bool TickStartupWarnings(float Dt);
    bool AdvanceStartupWarning(float Dt,bool Held);
    void UpdateTitleTimeline();
    bool DrawTitlePresentation();
    void DrawStartupWarning();
    void DrawBuildVersion();
    bool TitleTest=false;int TitleTestTicks=0,TitleTestCase=0,TitleTestCaptureBits=0,TitleTestSaveTicks=0;
    bool TitleTestInput=false;float TitleTestElapsed=0;
    void TickTitleTest(float Dt);
    int RomSetupTestTicks = 0;
    void StartVerifiedGame();
    TSharedPtr<struct FSMRomSetup> RomSetup;
    friend struct FSMSystemMenu;
    TSharedPtr<struct FSMSystemMenu> SystemMenu;
    int (*PauseData)(int)=nullptr;
    void (*SetBorder)(int)=nullptr;
    void (*ClearDecorations)()=nullptr;
    int (*SetDecoration)(int,int,int,int,int,int,int,int)=nullptr;
    int LoadRoomDecorations();
    bool BorderExtension=false;
    bool PauseTest=false;int PauseTestTicks=0;
    bool ObjectivePauseTest=false;
    bool PauseTestFailed=false;
    float FlashStrength=1;
    FString CoreRomPath,CoreSavePath,ProfilePath;
    int AchievementBits=0,AchievementItems=0,AchievementBeams=0;
    int AchievementKills=0,AchievementPower=0,AchievementGrapple=0,AchievementScrew=0;
    int AchievementTotalKills=0;bool AchievementPrimed=false;
    void ResetToTitle();
    UPROPERTY() TObjectPtr<UTexture2D> RouteTexture;
    bool RouteVisible=false,RoutePlaying=true,RouteAutoShown=false;
    int RouteCursor=0,RouteLastUploaded=-1,RouteSpeed=1;float RoutePosition=0;uint16 RoutePreviousButtons=0;
    void OpenRunRecap();bool TickRunRecap(float Dt);bool DrawRunRecap();
    bool AdvanceRunRecap(float Dt,uint16 Buttons,bool Close);
    void TrackAchievements();
    void TickPauseTest();
    const float* (*CinemaLights)()=nullptr;
    int (*CinemaState)(int)=nullptr;
    UPROPERTY() TObjectPtr<UTexture2D> CinemaTexture;
    void UpdateCinemaTexture();
    bool CinemaTest=false;int CinemaTestTicks=0,CinemaCase=1,CinemaSample=0;
    int (*TestCinematic)(int)=nullptr;
    void TickCinemaTest();
    FSMVisualEffects VisualEffects;
    int (*VisualState)(int,int)=nullptr;
    void (*SetCombatEffects)(int)=nullptr;
    int (*TestCombatEquipment)()=nullptr;
    int (*TestAllEquipment)()=nullptr;
    UPROPERTY() TObjectPtr<UTexture2D> EffectsTexture;
    TArray<FVector4f> EffectsPixels;
    void UpdateEffectsTexture();
    bool CombatTest=false;
    bool ElectricTest=false;int ElectricSnapshots=0;bool CapturedGrapple=false,CapturedScrew=false,CapturedEnemy=false;
    int (*TestRoom)(int,int,int)=nullptr;
    int (*TestAwaken)()=nullptr;
    bool DisplayTest=false;
    int DisplayTicks=0,DisplayCapture=0,DisplayMessages=0,DisplayDoors=0;
    bool DisplayPauseSeen=false;
    bool DisplayTimerSeen=false;
    int TestHoldState=-1;
    int (*TestMessage)(int)=nullptr;
    int (*TestEscapeTimer)()=nullptr;
    int CombatTicks=0,CombatSnapshots=0,LastBombCapture=-100;
    bool CapturedMuzzle=false,CapturedCharge=false,CapturedSplash=false,CapturedExplosion=false;
    bool Widescreen=true, WideTest=false;
    int ImageScaling=0; // 0: fit while preserving aspect, 1: integer pixel scaling.
    UPROPERTY() TObjectPtr<UTexture2D> GameOverWideTexture;
    UPROPERTY() TObjectPtr<UTexture2D> GameOverClassicTexture;
    UPROPERTY() TObjectPtr<UTexture2D> GameOverLabelsTexture;
    UPROPERTY() TObjectPtr<UTexture2D> GameOverDustTexture;
    UPROPERTY() TObjectPtr<UTexture2D> GameOverLampTexture;
    int (*GameOverState)(int)=nullptr;
    const uint8* (*GameOverLabels)()=nullptr;
    float GameOverTime=0;
    int GameOverLabelKey=-1,GameOverTestTicks=0;
    bool LastGameOverAudio=false,GameOverTest=false;
    void LoadGameOverPresentation();
    bool DrawGameOver();
    bool UseWide() const;
    void RefreshWide();
    void (*SetWidescreen)(int)=nullptr;
    int (*WideAvailable)()=nullptr;
    const uint8* (*WideScene)()=nullptr;
    const uint8* (*WideLayers)()=nullptr;
    const uint8* (*WideFar)()=nullptr;
    const uint8* (*WideHud)()=nullptr;
    UPROPERTY() TObjectPtr<UTexture2D> WideGameTexture;
    UPROPERTY() TObjectPtr<UTexture2D> WideSceneTexture;
    UPROPERTY() TObjectPtr<UTexture2D> WideMaskTexture;
    UPROPERTY() TObjectPtr<UTexture2D> WideHudTexture;
    TArray<uint8> WideDepthPixels,WideReliefPixels,WideMaskPixels;
    void* CoreHandle = nullptr;
    int (*Init)(const char*,const char*) = nullptr;
    int (*Step)(uint16) = nullptr;
    const uint8* (*Pixels)() = nullptr;
    const uint8* (*Scene)() = nullptr;
    const uint8* (*FarMask)() = nullptr;
    const uint8* (*Layers)() = nullptr;
    const uint8* (*Emission)() = nullptr;
    const uint8* (*Lightmap)() = nullptr;
    int (*ParallaxSupported)() = nullptr;
    void (*SetParallax)(int,int,int) = nullptr;
    const int16* (*Audio)() = nullptr;
    const char* (*Error)() = nullptr;
    int (*State)() = nullptr;
    int (*Frame)() = nullptr;
    int (*SamusX)() = nullptr;
    int (*SamusY)() = nullptr;
    int (*Room)() = nullptr;
    int (*Area)() = nullptr;
    int (*CameraX)() = nullptr;
    int (*CameraY)() = nullptr;
    int (*MessageActive)() = nullptr;
    int (*PresentationKind)() = nullptr;
    const uint8* (*UiOverlay)() = nullptr;
    UPROPERTY() TObjectPtr<UTexture2D> UiTexture;
    int (*FxType)() = nullptr;
    int (*WaterY)() = nullptr;
    int (*HeatedRoom)() = nullptr;
    void (*SetEngineWeather)(int) = nullptr;
    void (*SetAssistedWallJump)(int) = nullptr;
    bool AssistedWallJump = true;
    void (*SetAssistedSpaceJump)(int) = nullptr;
    bool AssistedSpaceJump = true;
    int (*Teleport)(int) = nullptr;
    int (*TeleportCount)() = nullptr;
    const char* (*TeleportName)(int) = nullptr;
    bool TeleportMenu = false;
    bool TeleportUiTest = false;
    int TeleportUiTicks = 0, TeleportUiFrame = 0;
    void TickTeleportUiTest();
    int TeleportSelection = 0;
    bool CreditsTest=false;int CreditsTestTicks=0,CreditsTestFrame=0,LastCreditsMode=0;
    void TickCreditsTest();
    int (*CreditsState)(int) = nullptr;
    int (*Brightness)() = nullptr;
    uint64 (*Opcodes)() = nullptr;
    void (*Shutdown)() = nullptr;
    int (*Save)() = nullptr;
    UPROPERTY() TObjectPtr<UTexture2D> GameTexture;
    UPROPERTY() TObjectPtr<UTexture2D> SceneTexture;
    UPROPERTY() TObjectPtr<UTexture2D> EmissionTexture;
    UPROPERTY() TObjectPtr<UTexture2D> LightTexture;
    UPROPERTY() TObjectPtr<UTexture2D> EnvironmentMaskTexture;
    TArray<uint8> EnvironmentMaskPixels;
    UPROPERTY() TObjectPtr<USoundWaveProcedural> AudioWave;
    UPROPERTY() TObjectPtr<UAudioComponent> AudioComponent;
    UPROPERTY() TObjectPtr<UMaterialInstanceDynamic> PresentMaterial;
    double Accumulator = 0;
    int LastState = -1;
    int TestFrames = 0;
    int CapturedAt = 0;
    bool Ready = false;
    bool Paused = false;
    bool Atmosphere = true;
    bool ShowHelp = false;
    bool PixelTest = false;
    bool EngineWeather = true;
    bool WeatherTest = false;
    int WeatherTestCase = 0;
    float WeatherTime = 0;
    void UpdateEnvironmentMask();
    bool DepthTest = false;
    bool ReliefTest = false;
    bool Relief = true;
    TArray<uint8> ReliefPixels;
    bool DepthMotion = false;
    int MotionTicks = 0;
    bool Depth = true;
    TArray<uint8> DepthPixels;
    void RefreshScenePresentation();
    int FreezeTicks = 0;
    float Intensity = 0.35f;
    int BlendMode = 0; // 0: Lighten, 1: Multiply
    bool Parallax = true;
    int PresentationRoom = -1, AnchorX = 0, AnchorY = 0;
    float Exposure = 1.0f;
    FString SettingsPath;
    FString Notice;
    double NoticeUntil = 0;
    void PersistSettings();
    void NotifySettings();
    void UpdatePresentation();
    bool RelicTest=false;int RelicTestFrame=0,RelicCollectedFrame=0,RelicDismissedFrame=0;
    int (*RelicCount)()=nullptr;
    bool AutoTest = false;
    bool PlaytestCheck=false,RecapCheck=false,SporeCheck=false;int PlaytestTicks=0;
    void TickPlaytestCheck();
    bool FootstepTest=false;
    int FootstepTicks=0;
    bool FootstepCaptured[6]={};
    FString Failure;
    uint16 ReadButtons() const;
};
