// Pinned source Scavenger identities. Generated by build-scavenger.py.
static const TCHAR* NativeScavengerCatalog=TEXT("976966c88a9ed9997f193bf6dc9033e2ffd6bc01f0d9bee40d4735c001ebe659");
static const struct {uint16 Word; const TCHAR* Name;} NativeScavengerSpecs[]={
{6656,TEXT("Morphing Ball")},
{1793,TEXT("Bomb")},
{5890,TEXT("Charge Beam")},
{10755,TEXT("Spazer")},
{12292,TEXT("Varia Suit")},
{13573,TEXT("Hi-Jump Boots")},
{12806,TEXT("Ice Beam")},
{16903,TEXT("Speed Booster")},
{17416,TEXT("Wave Beam")},
{15369,TEXT("Grapple Beam")},
{9738,TEXT("X-Ray Scope")},
{34571,TEXT("Gravity Suit")},
{39436,TEXT("Space Jump")},
{38413,TEXT("Spring Ball")},
{36622,TEXT("Plasma Beam")},
{20239,TEXT("Screw Attack")},
{43536,TEXT("Ridley")},
};
