/* Generated from the same pinned objective catalog as native C. */
static const TCHAR* NativeObjectiveCatalog=TEXT("a752e646fb5e28d7e39c41f41f971e6c897bf76a5538fa1cc4d5b394bc025324");
static const struct {const TCHAR* Name; bool Supported;} NativeObjectiveSpecs[]={
{TEXT("kill kraid"),true},
{TEXT("kill phantoon"),true},
{TEXT("kill draygon"),true},
{TEXT("kill ridley"),true},
{TEXT("kill one G4"),true},
{TEXT("kill two G4"),true},
{TEXT("kill three G4"),true},
{TEXT("kill all G4"),true},
{TEXT("kill spore spawn"),true},
{TEXT("kill botwoon"),true},
{TEXT("kill crocomire"),true},
{TEXT("kill golden torizo"),true},
{TEXT("kill one miniboss"),true},
{TEXT("kill two minibosses"),true},
{TEXT("kill three minibosses"),true},
{TEXT("kill all mini bosses"),true},
{TEXT("finish scavenger hunt"),false},
{TEXT("nothing"),true},
{TEXT("collect 25% items"),true},
{TEXT("collect 50% items"),true},
{TEXT("collect 75% items"),true},
{TEXT("collect 100% items"),true},
{TEXT("collect all upgrades"),true},
{TEXT("clear crateria"),true},
{TEXT("clear green brinstar"),true},
{TEXT("clear red brinstar"),true},
{TEXT("clear wrecked ship"),true},
{TEXT("clear kraid's lair"),true},
{TEXT("clear upper norfair"),true},
{TEXT("clear croc's lair"),true},
{TEXT("clear lower norfair"),true},
{TEXT("clear west maridia"),true},
{TEXT("clear east maridia"),true},
{TEXT("explore 25% map"),true},
{TEXT("explore 50% map"),true},
{TEXT("explore 75% map"),true},
{TEXT("explore 100% map"),true},
{TEXT("explore crateria"),true},
{TEXT("explore green brinstar"),true},
{TEXT("explore red brinstar"),true},
{TEXT("explore wrecked ship"),true},
{TEXT("explore kraid's lair"),true},
{TEXT("explore upper norfair"),true},
{TEXT("explore croc's lair"),true},
{TEXT("explore lower norfair"),true},
{TEXT("explore west maridia"),true},
{TEXT("explore east maridia"),true},
{TEXT("tickle the red fish"),true},
{TEXT("kill the orange geemer"),true},
{TEXT("kill shaktool"),true},
{TEXT("activate chozo robots"),true},
{TEXT("visit the animals"),true},
{TEXT("kill king cacatac"),true},
{TEXT("kill all space pirates"),true},
{TEXT("kill all ki hunters"),true},
{TEXT("kill all beetoms"),true},
{TEXT("kill all cacatacs"),true},
{TEXT("kill all kagos"),true},
{TEXT("kill all yapping maws"),true},
};
static const uint16 NativeObjectiveMapTotals[2][12]={
{0,165,145,67,141,25,185,55,121,96,170,0},
{0,158,146,63,139,25,179,55,132,96,172,0},
};
