// Generated immutable area endpoint order.
static const TArray<FString> NativeAreaNames={
TEXT("Aqueduct Top Left"),
TEXT("Caterpillar Room Top Right"),
TEXT("Crab Hole Bottom Left"),
TEXT("Crab Maze Left"),
TEXT("Crab Shaft Right"),
TEXT("Crocomire Room Top"),
TEXT("Crocomire Speedway Bottom"),
TEXT("East Tunnel Right"),
TEXT("East Tunnel Top Right"),
TEXT("Glass Tunnel Top"),
TEXT("Golden Four"),
TEXT("Green Brinstar Elevator"),
TEXT("Green Hill Zone Top Right"),
TEXT("Green Pirates Shaft Bottom Right"),
TEXT("Keyhunter Room Bottom"),
TEXT("Kronic Boost Room Bottom Left"),
TEXT("Lava Dive Right"),
TEXT("Le Coude Right"),
TEXT("Lower Mushrooms Left"),
TEXT("Main Street Bottom"),
TEXT("Moat Right"),
TEXT("Morph Ball Room Left"),
TEXT("Noob Bridge Right"),
TEXT("Red Brinstar Elevator"),
TEXT("Red Fish Room Left"),
TEXT("Red Tower Top Left"),
TEXT("Single Chamber Top Right"),
TEXT("Three Muskateers Room Left"),
TEXT("Warehouse Entrance Left"),
TEXT("Warehouse Entrance Right"),
TEXT("Warehouse Zeela Room Left"),
TEXT("West Ocean Left"),
};
