#pragma once
#include <stdint.h>
#ifdef __cplusplus
extern "C" {
#endif
#if defined(_WIN32)
#if defined(SM_NATIVE_BUILD)
#define SM_API __declspec(dllexport)
#else
#define SM_API __declspec(dllimport)
#endif
#else
#define SM_API __attribute__((visibility("default")))
#endif
/* Single instance, all calls on the game thread. Audio is generated by step. */
SM_API const uint8_t *sm_window_icon_pixels(void); /* Valid only after successful sm_init. */
SM_API int sm_init(const char *rom_path, const char *sram_path);
SM_API int sm_step(uint16_t buttons);
SM_API const uint8_t *sm_pixels(void); /* BGRA8, 256 x 240 */
SM_API const int16_t *sm_audio(void); /* 736 stereo frames at 44100Hz */
SM_API const char *sm_error(void);
SM_API int sm_state(void);
SM_API int sm_frame(void);
SM_API uint64_t sm_cpu_opcodes(void);
SM_API uint64_t sm_simulation_hash(void);
SM_API double sm_profile_us(int field);
SM_API void sm_set_fast_scene_render(int enabled);
SM_API const uint8_t *sm_simulation_ram(void);
SM_API int sm_samus_x(void);
SM_API int sm_samus_y(void);
SM_API int sm_room(void);
SM_API int sm_test_boss_connection(int source_index);
SM_API int sm_test_area_connection(int source_index);
SM_API int sm_area(void);
SM_API int sm_camera_x(void);
SM_API int sm_camera_y(void);
SM_API int sm_brightness(void);
SM_API int sm_message_active(void);
/* 0: menus/loading, 1: world (including messages/fades), 2: cinematic. */
SM_API int sm_presentation_kind(void);
SM_API const uint8_t *sm_ui_overlay(void);
SM_API int sm_test_all_equipment(void); /* isolated SMTests saves only */
SM_API int sm_test_rendering(int enabled); /* isolated logic replays; no pixel claims when disabled */
SM_API int sm_test_message(int index); /* native dialog lifecycle, isolated saves */
SM_API int sm_test_escape_timer(void);
SM_API int sm_fx_type(void);
SM_API int sm_water_y(void); /* world surface; 32767 means no active water */
SM_API int sm_heated_room(void);
SM_API void sm_set_engine_weather(int enabled);
SM_API int sm_teleport_count(void);
SM_API const char *sm_teleport_name(int destination);
SM_API int sm_teleport_room(int destination);
SM_API int sm_teleport(int destination); /* stable gameplay only; 0 = unavailable */
SM_API void sm_set_assisted_walljump(int enabled);
SM_API int sm_assisted_walljump(void);
SM_API void sm_set_assisted_spacejump(int enabled);
SM_API int sm_assisted_spacejump(void);
SM_API int sm_player_motion(int field); /* 0 movement, 1 pose, 2 vertical direction, 3 health */
SM_API const uint8_t *sm_scene(void);
SM_API const uint8_t *sm_background_mask(void);
SM_API const uint8_t *sm_emission(void);
SM_API const uint8_t *sm_lightmap(void);
SM_API int sm_parallax_supported(void);
SM_API const uint8_t *sm_layers(void);
SM_API void sm_set_parallax(int x,int y,int enabled);
SM_API const uint8_t *sm_vram(void);
SM_API const uint16_t *sm_palette(void);
SM_API const uint8_t *sm_oam(void);
SM_API int sm_ppu_mode(void);
SM_API int sm_bg_info(int layer,int field);
SM_API void sm_set_widescreen(int enabled);
SM_API const uint8_t *sm_wide_scene(void);
SM_API const uint8_t *sm_wide_metadata(void);
SM_API const uint8_t *sm_wide_background(void);
SM_API const uint8_t *sm_wide_overlay(void);
SM_API int sm_wide_available(void);
SM_API int sm_view_margin(void);
SM_API void sm_set_border_extension(int enabled);
SM_API int sm_border_stat(int field);
SM_API void sm_decor_clear(void);
SM_API int sm_decor_set(int room,int state,int tileset,int layer,int x,int y,int tile,int expected);
SM_API int sm_decor_room_active(void);
SM_API int sm_decor_get(int layer,int x,int y,uint16_t *tile);
SM_API const uint8_t *sm_pause_map(void); /* BGRA 512x256, original map tiles */
SM_API const uint8_t *sm_pause_wire(void); /* BGRA 64x136, original suit variants */
SM_API const uint8_t *sm_pause_atlas(void); /* BGRA 128x256, original pause tiles */
SM_API int sm_pause_data(int field);
SM_API int sm_pause_action(int action,int index);
SM_API int sm_test_room(int room,int x,int y);
SM_API int sm_test_awaken(void);
void sm_test_load_room(void);
SM_API int sm_save(void);
SM_API void sm_shutdown(void);
#ifdef __cplusplus
}
#endif

SM_API int sm_test_credits_ending(void); /* isolated SMTests saves only */
SM_API int sm_test_map_explored(int explored); /* isolated SMTests map-render fixture */

SM_API int sm_test_cinematic(int scene);

/* Isolated regression fixtures only; rejected outside an SMTests save path. */
SM_API int sm_test_playtest(int action,int value);
