#!/usr/bin/env python3
"""Extract the pinned start dependencies and IPS spans for native-port review.
Does not generate a seed, launch the game or alter the upstream checkout.
"""
from pathlib import Path
import sys,json,hashlib
root=Path(__file__).resolve().parents[1];upstream=root/'Randomizer/upstream'
sys.path.insert(0,str(upstream))
from logic.logic import Logic
Logic.factory('vanilla')
from rom.flavor import RomFlavor
RomFlavor.factory(str(upstream))
from graph.graph_utils import GraphUtils,getAccessPoint
from rom.rom_patches import getPatchSet,groups
from rom.ips import IPS_Patch
pa=RomFlavor.patchAccess
patches={};starts=[]
def collect(name):
 if name in patches:return
 if name in pa.getDictPatches():
  data=pa.getDictPatches()[name];origin='dictionary'
 else:
  path=Path(pa.getPatchPath(name));data=IPS_Patch.load(str(path)).toDict();origin=str(path.relative_to(upstream))
 spans=[]
 for address,values in sorted(data.items()):
  spans.append(dict(address=address,snes=((address//0x8000|0x80)<<16)|(address%0x8000|0x8000),size=len(values),sha256=hashlib.sha256(bytes(values)).hexdigest()))
 patches[name]=dict(source=origin,spans=spans,additionalPlm=pa.getAdditionalPLMs().get(name))
for name in GraphUtils.getStartAccessPointNames():
 ap=getAccessPoint(name);start=dict(ap.Start);deps=[]
 for key in ('save','rom_patches'):
  values=start.get(key,[]);values=[values] if isinstance(values,str) else values
  for patch in values:collect(patch);deps.append(patch)
 sets={}
 for group in ('layout','areaLayout','variaTweaks'):
  sets[group]=[]
  for patchset in start.get(group,[]):
   definition=getPatchSet(patchset,'vanilla')
   for patch in definition.get('ips',[]):collect(patch);sets[group].append(patch)
 starts.append(dict(name=name,start=start,directPatches=deps,conditionalGroups=sets))
# Include every individual non-cosmetic layout/tweak group, so the same
# reviewed data layer can serve custom seed options and forced start patches.
for group,names in groups.items():
 for name in names:
  for patch in getPatchSet(name,'vanilla').get('ips',[]):collect(patch)
for patch in getPatchSet('boss','vanilla').get('ips',[]):collect(patch)
result=dict(upstream='72ec1f30b700442d0c30aad6c43801bd64f1e2a5',starts=starts,patches=patches)
out=root/'Docs/Randomizer/FullOptions/Starts';out.mkdir(exist_ok=True)
(out/'dependencies.json').write_text(json.dumps(result,indent=2)+'\n')
lines=['# Pinned native-start and layout patch spans','', 'Generated by `Scripts/audit-native-starts.py`. These are source dependencies, not a claim of implemented native behavior.','']
for name,patch in patches.items():
 spans=', '.join(f"${s['snes']:06X} ({s['size']} bytes)" for s in patch['spans'])
 lines.append(f'- `{name}`: {spans}'+(' + additional room PLM' if patch['additionalPlm'] else ''))
(out/'patch-spans.md').write_text('\n'.join(lines)+'\n')
print(len(starts),'start definitions;',len(patches),'patch definitions')
