#!/usr/bin/env python3
"""Bake reviewed source identities, never classify arbitrary bright screen pixels."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
rules=json.loads((root/'Config/lighting-sources.json').read_text())
manifest=json.loads((root/'Docs/LightingAudit/Inventory/manifest.json').read_text())
rom=(root/'roms/Super Metroid (Japan, USA) (En,Ja).sfc').read_bytes()
def off(a): return ((a>>16)&127)*32768+(a&32767)
def fnv(b):
    h=2166136261
    for x in b:h=((h^x)*16777619)&0xffffffff
    return h
lines=['/* Generated by Scripts/bake-lighting.py from reviewed source rules. */',
       'typedef struct { uint32_t hash; uint8_t mode; uint32_t indices[8]; } SmEmitterRule;',
       'static const SmEmitterRule emitter_rules[] = {']
entries=[]
for r in rules['mode7']:entries.append((int(r['hash'],16),7,r['indices']))
for r in manifest['records']:
    if r.get('definition') not in rules['fire_sprite_definitions']:continue
    start=off(int(r['graphics_pointer'],16)); data=rom[start:start+r['bytes']]
    # Index zero is transparent; dim outlines of approved flame art stay dark.
    pal=off(int(r['palette_pointer'],16));indices=[]
    for i in range(1,16):
        c=int.from_bytes(rom[pal+i*2:pal+i*2+2],'little')
        if max(c&31,(c>>5)&31,(c>>10)&31)>=18:indices.append(i)
    for t in range(0,len(data),32):
        if any(data[t:t+32]):entries.append((fnv(data[t:t+32]),4,indices))
seen=set()
for h,m,idx in entries:
    key=(h,m,tuple(idx))
    if key in seen:continue
    seen.add(key);bits=[sum(1<<(i%32) for i in idx if i//32==w) for w in range(8)]
    lines.append('{0x%08xu,%d,{%s}},'%(h,m,','.join('0x%xu'%v for v in bits)))
lines.append('};')
(root/'Native/sm_emitters.generated.h').write_text('\n'.join(lines)+'\n')
print('Baked',len(seen),'reviewed tile rules')
