#!/usr/bin/env python3
"""Extract authored VARIA pause assets/data; never install executable IPS bytes."""
import hashlib,json,struct,sys
from ui_rom_assets import recipe
from pathlib import Path
root=Path(__file__).resolve().parents[1];upstream=root/'Randomizer/upstream'
sys.path.insert(0,str(upstream))
from logic.logic import Logic
Logic.factory('vanilla')
from utils.objectives import Objectives
from rom.rom import snes_to_pc
def ips(path):
    raw=path.read_bytes();assert raw[:5]==b'PATCH';pos=5;data={}
    while raw[pos:pos+3]!=b'EOF':
        address=int.from_bytes(raw[pos:pos+3],'big');size=int.from_bytes(raw[pos+3:pos+5],'big');pos+=5
        if size:payload=raw[pos:pos+size];pos+=size
        else:
            count=int.from_bytes(raw[pos:pos+2],'big');payload=bytes([raw[pos+2]])*count;pos+=3
        data.update({address+i:v for i,v in enumerate(payload)})
    return data
def extract(data,address,size):return bytes(data[snes_to_pc(address)+i] for i in range(size))
source=upstream/'patches/common/src';patches=upstream/'patches/common/ips'
symbols=json.loads((upstream/'patches/common/sym/objectives.json').read_text())
base=extract(ips(patches/'objectives.ips'),symbols['obj_bg1_tilemap'],19*32*2)
palettes=extract(ips(patches/'map.ips'),0xb6f000,256)
gfx=(source/'map/pause.gfx').read_bytes()[:0x4000]
chars={line.split('=',1)[1]:int(line.split('=',1)[0],16) for line in (source/'tables/pause.tbl').read_text().splitlines() if '=' in line}
labels=[]
catalog=json.loads((root/'Randomizer/native_objectives.json').read_text())
for entry in catalog['goals']:
    goal=Objectives.goals[entry['name']]
    # "Kill" is an original VARIA synonym; keep deterministic authored labels
    # instead of selecting fresh cosmetic synonyms when loading a saved seed.
    text=(goal.text.format('Kill') if goal.useSynonym else goal.text).rstrip()
    assert len('18.'+text)<=27,(goal.name,text)
    assert all(c in chars for c in text),(goal.name,text)
    labels.append(dict(id=entry['id'],name=goal.name,text=text,progress=bool(goal.inProgressSymbol),
                       startEvent=147+entry['arg'] if entry['kind']=='area_clear' else 0,
                       nonzero=entry['kind']=='enemy_family'))
words=lambda raw:list(struct.unpack('<'+'H'*(len(raw)//2),raw))
# The native footer retains EXIT/START and the authored L/R labels. VARIA's
# font replaces some of those graphic indices. Allocate separate copies only
# while the objective page is active; never replace original glyph pixels.
rom=(root/'roms/Super Metroid (Japan, USA) (En,Ja).sfc').read_bytes()
assert hashlib.sha1(rom).hexdigest()=='da957f0d63d14cb441d215462904c4fa8519c613'
frame=words(rom[snes_to_pc(0xb6e000):snes_to_pc(0xb6e000)+0x800])
used={v&1023 for v in frame+words(base)+list(chars.values())}|{0x176,0x177,0x1b8}|set(range(0x1f8,0x200))
free=[i for i in range(2,512) if i not in used]
footer_tiles=sorted({v&1023 for v in frame[800:864]}-{1})
assert len(free)>=len(footer_tiles)
relocations=list(zip(footer_tiles,free))
lines=['/* Original VARIA data; generated by build-objective-pause.py. */']
def array(name,kind,values,hexadecimal=False):
    lines.append(f'static const {kind} {name}[{len(values)}]={{')
    for i in range(0,len(values),16):lines.append(','.join(hex(v) if hexadecimal else str(v) for v in values[i:i+16])+',')
    lines.append('};')
needed={v&1023 for v in words(base)+list(chars.values())}|{0x176,0x177,0x1b8}|set(range(0x96,0x99))|set(range(0xa6,0xa9))
lines+=recipe(root,'objective_pause_gfx',gfx,4,0xb68000,16384,needed)
array('objective_pause_base','uint16_t',words(base),True)
array('objective_pause_palettes','uint16_t',words(palettes),True)
lines.append('static const uint16_t objective_pause_footer_tiles[][2]={')
lines += ['{'+hex(src)+','+hex(dst)+'},' for src,dst in relocations]
lines.append('};')
array('objective_pause_chars','uint16_t',[chars.get(chr(i),0) for i in range(128)],True)
lines+=['static const struct {const char *text;uint8_t progress,start_event,nonzero;} objective_pause_labels[]={']
lines+=['{'+json.dumps(label['text'])+','+','.join(str(int(label[k])) for k in ['progress','startEvent','nonzero'])+'},' for label in labels]
lines+=['};']
(root/'Native/sm_objective_pause_assets.inc').write_text('\n'.join(lines)+'\n')
out=root/'Docs/Randomizer/FullOptions/Objectives/Presentation';out.mkdir(parents=True,exist_ok=True)
paths=[patches/'objectives.ips',patches/'map.ips',source/'map/pause.gfx',source/'map/pause_map_tilemap.bin',source/'tables/pause.tbl',source/'objectives.asm',upstream/'utils/objectives.py']
audit=dict(schema=1,sources={str(p.relative_to(upstream)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths},
           labels=labels,characters=chars,base=words(base),palettes=words(palettes),gfxSha256=hashlib.sha256(gfx).hexdigest(),
           footerRelocations=relocations,originalRomSha256=hashlib.sha256(rom).hexdigest(),
           textPolicy='Original goal text with fixed original Kill synonym; rank and progress are native values')
(out/'assets.json').write_text(json.dumps(audit,indent=2)+'\n')
print('OBJECTIVE_PAUSE_ASSETS',len(labels),'labels;',len(base),'tilemap bytes;',len(gfx),'graphics bytes')
