#!/usr/bin/env python3
"""Original VARIA objective-number sprites and full-layout map memberships."""
import hashlib,json,re,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1];up=root/'Randomizer/upstream'
sys.path.insert(0,str(up))
from logic.logic import Logic
Logic.factory('vanilla')
from utils.objectives import Objectives
from graph.graph_utils import gameAreas,graphAreas
source=up/'patches/common/src/map'
gfx=(source/'pause_extra.gfx').read_bytes()
palette_line=re.search(r'org \$b6f1e0\s+dw ([^\n]+)',(source/'pause_palettes.asm').read_text()).group(1)
palette=[int(v.strip()[1:],16) for v in palette_line.split(',')];assert len(palette)==16
asm=(source/'mapicon_sprites.asm').read_text();sprites=[]
for rank in range(1,19):
    match=re.search(r'objective_'+str(rank)+r':\s+dw \$([\da-f]+) : db \$([\da-f]+) : dw \$([\da-f]+)',asm)
    x,y,word=(int(v,16) for v in match.groups());tile=word&0x1ff
    assert x==1 and y==255 and (word>>9)&7==7 and not word&0xc000
    raw=gfx[(tile-0xcb)*32:(tile-0xcb+1)*32];assert len(raw)==32
    pixels=[]
    for dy in range(8):
        for dx in range(8):
            ci=sum(((raw[plane//2*16+dy*2+plane%2]>>(7-dx))&1)<<plane for plane in range(4))
            pixels.append(palette[ci] if ci else 65535)
    sprites.append(dict(rank=rank,x=x,y=-1,word=word,pixels=pixels))
catalog=json.loads((root/'Randomizer/native_objectives.json').read_text())
points=[];names={};spots={}
for name,data in Logic.map_tiles.objectives.items():
    area=gameAreas.index(data['area']);x,y=data['map_coords_px'];key=(area,x,y)
    if key not in spots:spots[key]=len(spots)
    names[name]=len(points)
    points.append(dict(name=name,area=area,x=x,y=y,event=data['event'],spot=spots[key],graphArea=data.get('graphArea')))
categories=list(dict.fromkeys(g.category for g in Objectives.goals.values()))
goals=[];members=[]
for entry in catalog['goals']:
    goal=Objectives.goals[entry['name']];ids=[names[n] for n in goal.mapIcons]
    goals.append(dict(id=entry['id'],name=goal.name,category=goal.category,categoryId=categories.index(goal.category),offset=len(members),points=ids))
    members+=ids
assert len(points)<256 and len(spots)<256 and len(members)<65536
lines=['/* Original VARIA map data, generated by build-objective-map.py. */',
       f'#define OBJECTIVE_MAP_SPOTS {len(spots)}',f'#define OBJECTIVE_MAP_MEMES {categories.index("Memes")}',
       'static const uint16_t objective_map_sprites[18][64]={']
lines+=['{'+','.join(map(str,s['pixels']))+'},' for s in sprites]
lines+=['};','static const struct {uint16_t x,y,event;uint8_t area,spot,region;} objective_map_points[]={']
lines+=['{%d,%d,%d,%d,%d,%d},'%(p['x'],p['y'],p['event'],p['area'],p['spot'],graphAreas.index(p['graphArea']) if p['graphArea'] is not None else 255) for p in points]
lines+=['};','static const uint8_t objective_map_members[]={'+','.join(map(str,members))+'};',
        'static const struct {uint16_t offset;uint8_t count,category;} objective_map_goals[]={']
lines+=['{%d,%d,%d},'%(g['offset'],len(g['points']),g['categoryId']) for g in goals]
lines+=['};']
(root/'Native/sm_objective_map.inc').write_text('\n'.join(lines)+'\n')
paths=[source/'pause_extra.gfx',source/'pause_palettes.asm',source/'mapicon_sprites.asm',source/'PauseScreenRoutines.asm',up/'utils/objectives.py',up/'graph/vanilla/map_tiles.py',up/'rom/rompatcher.py']
audit=dict(schema=1,conditionCatalogSha256=catalog['sha256'],sprites=sprites,points=points,goals=goals,spotCount=len(spots),
           sources={str(p.relative_to(up)):hashlib.sha256(p.read_bytes()).hexdigest() for p in paths})
out=root/'Docs/Randomizer/FullOptions/Objectives/MapDependencies';out.mkdir(exist_ok=True)
(out/'map-audit.json').write_text(json.dumps(audit,indent=2)+'\n')
print('OBJECTIVE_MAP_ASSETS',len(sprites),'sprites;',len(points),'points;',len(spots),'positions')
