#!/usr/bin/env python3
"""Compile original VARIA portal/door sprites and map coordinates for C.

No generated artwork or ROM edits. Routing catalogs remain immutable.
"""
import hashlib,json,re,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1];upstream=root/'Randomizer/upstream'
sys.path.insert(0,str(upstream))
from logic.logic import Logic
Logic.factory('vanilla')
from rom.map import AreaMap,portal_mapicons
from graph.graph_utils import gameAreas,getAccessPoint
from utils.doorsmanager import doors_mapicons

source=upstream/'patches/common/src/map'
gfx=(source/'pause_extra.gfx').read_bytes();assert len(gfx)==0x6a0
constants={name:int(value,16) for name,value in re.findall(r'!(AreaColor_\w+)\s*=\s*\$([0-9a-fA-F]+)',((upstream/'patches/common/src/include/area_colors.asm').read_text()+(source/'config/MaptileGlow.asm').read_text()))}
palettes={};address=0
for line in (source/'pause_palettes.asm').read_text().splitlines():
    line=line.split(';')[0].strip()
    if line.startswith('org '):address=int(line[5:],16) if line.startswith('org $') else 0
    elif line.startswith('dw ') and 0xb6f180<=address<0xb6f1c0:
        values=[constants[v[1:]] if v.startswith('!') else int(v[1:],16) for v in line[3:].split(',') for v in [v.strip()]]
        for value in values:palettes[address]=value;address+=2
assert len(palettes)==32

def pixels(icon):
    # VARIA_init uploads pause_extra.gfx at VRAM word $2CB0. OBJ base
    # is $2000, so this replaces sprite indices $CB..$FF.
    assert 0xcb<=icon.idx<=0xff
    tile=gfx[(icon.idx-0xcb)*32:(icon.idx-0xcb+1)*32];assert len(tile)==32
    result=[]
    for y in range(8):
        for x in range(8):
            row=7-y if icon.vFlip else y;bit=x if icon.hFlip else 7-x
            ci=sum(((tile[(plane//2)*16+row*2+plane%2]>>bit)&1)<<plane for plane in range(4))
            result.append(palettes[0xb6f100+icon.pal*32+ci*2] if ci else 65535)
    assert any(c!=65535 for c in result)
    return result

icons=[]
def add(name,icon):
    idx=len(icons);icons.append(dict(name=name,x=icon.X if icon.X<256 else icon.X-512,
        y=icon.Y if icon.Y<128 else icon.Y-256,word=icon.toWord(),pixels=pixels(icon)))
    return idx
portal_ids={name:add('portal_'+name,icon) for name,icon in portal_mapicons.items()}
colors=json.loads((root/'Randomizer/native_door_colors.json').read_text())
door_icons=[]
for color in colors['colors']:
    door_icons.append([-1]*4 if color=='blue' else [add('door_'+color+'_'+str(facing),doors_mapicons[(color,facing)]) for facing in range(4)])
asm=(source/'mapicon_sprites.asm').read_text()
records={(int(x,16),int(y,16),int(w,16)) for x,y,w in re.findall(r'dw \$([0-9a-f]+) : db \$([0-9a-f]+) : dw \$([0-9a-f]+)',asm)}
assert all((i['x']&511,i['y']&255,i['word']) in records for i in icons)
assert '%gfxDMA(extra_gfx, $2CB0, !extra_gfx_size)' in (source/'PauseScreenRoutines.asm').read_text()

amap=AreaMap()
def position(info):
    x,y=info.get('coords',amap.getCoordsByte(info.get('byteIndex',0),info.get('bitMask',1)))
    byte,mask=amap.getByteIndexMask(x,y)
    return dict(area=gameAreas.index(info['area']),x=x,y=y,byte=byte,mask=mask)
domains={}
for domain,catalog_name in [('area','native_areas.json'),('boss','native_connections.json')]:
    catalog=json.loads((root/'Randomizer'/catalog_name).read_text());entries=[]
    for ap in catalog['accessPoints']:
        name=ap['name'];actual=(Logic.map_tiles.areaAccessPoints if domain=='area' else Logic.map_tiles.bossAccessPoints)[name]
        display=Logic.map_tiles.areaAccessPointsInGameDisplay.get(name,actual)
        dest={'KraidRoomIn':'KraidBoss','PhantoonRoomIn':'PhantoonBoss','DraygonRoomIn':'DraygonBoss','RidleyRoomIn':'RidleyBoss'}.get(name,getAccessPoint(name).GraphArea)
        entries.append(dict(id=ap['id'],name=name,display=position(display),actual=position(actual),
            destinationIcon=portal_ids[dest],relocated=display is not actual,coversTile=bool(display.get('coversTile'))))
    domains[domain]=entries
doors=[]
for loc in colors['locations']:
    if loc['name'] not in Logic.map_tiles.doors:continue
    info=Logic.map_tiles.doors[loc['name']]
    doors.append(dict(id=loc['id'],name=loc['name'],position=position(info),facing=loc['facing'],openedBit=loc['openedBit']))

audit=dict(schema=1,upstream='72ec1f30b700442d0c30aad6c43801bd64f1e2a5',
    assets={str(p.relative_to(upstream)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [source/'pause_extra.gfx',source/'pause_palettes.asm',source/'mapicon_sprites.asm',source/'PauseScreenRoutines.asm',source/'config/MaptileGlow.asm',upstream/'patches/common/src/include/area_colors.asm']},
    icons=icons,doorIcons=door_icons,domains=domains,doors=doors,unexploredIcon=portal_ids['Unexplored'])
lines=['/* Original VARIA pixels and map coordinates; generated by build-map-icons.py. */',
       'typedef struct {uint8_t area,x,y,byte,mask;} MapIconPosition;',
       'static const struct {int8_t x,y;uint16_t pixels[64];} map_icon_sprites[]={']
lines+=['{%d,%d,{%s}},'%(s['x'],s['y'],','.join(map(str,s['pixels']))) for s in icons]
lines+=['};','static const int8_t map_door_sprites[9][4]={']
lines+=['{'+','.join(map(str,row))+'},' for row in door_icons]
lines+=['};',f'#define MAP_UNKNOWN_PORTAL {portal_ids["Unexplored"]}',
       'typedef struct {MapIconPosition display,actual;uint8_t sprite;} MapPortal;']
def cpos(p):return '{%d,%d,%d,%d,%d}'%(p['area'],p['x'],p['y'],p['byte'],p['mask'])
for domain,entries in domains.items():
    lines.append('static const MapPortal map_'+domain+'_portals[]={')
    lines+=['{%s,%s,%d},'%(cpos(e['display']),cpos(e['actual']),e['destinationIcon']) for e in entries]
    lines.append('};')
lines.append('static const struct {MapIconPosition position;uint8_t id,facing,opened_bit;} map_door_positions[]={')
lines+=['{%s,%d,%d,%d},'%(cpos(e['position']),e['id'],e['facing'],e['openedBit']) for e in doors]
lines.append('};')
(root/'Native/sm_map_icons.inc').write_text('\n'.join(lines)+'\n')
out=root/'Docs/Randomizer/FullOptions/MapIcons';out.mkdir(exist_ok=True)
(out/'audit.json').write_text(json.dumps(audit,indent=2)+'\n')
print('MAP_ICONS',len(icons),'sprites',len(doors),'doors',sum(map(len,domains.values())),'portals')
