#!/usr/bin/env python3
"""Decode original ROM/VARIA assets and authored credit data; no generated art."""
from pathlib import Path
import re,json,hashlib
root=Path(__file__).resolve().parents[1]
rom=next((root/'roms').glob('*.sfc')).read_bytes()
assert hashlib.sha1(rom).hexdigest()=='da957f0d63d14cb441d215462904c4fa8519c613'
def pc(a):return ((a>>16)&127)*32768+(a&32767)
def dec(a):
 i=pc(a);out=bytearray()
 while True:
  b=rom[i];i+=1
  if b==255:return out
  cmd=b>>5;n=(b&31)+1
  if cmd==7:cmd=(b>>2)&7;n=((b&3)<<8|rom[i])+1;i+=1
  if cmd==0:out+=rom[i:i+n];i+=n
  elif cmd==1:out+=bytes([rom[i]])*n;i+=1
  elif cmd==2:out+=bytes(rom[i+j%2] for j in range(n));i+=2
  elif cmd==3:out+=bytes((rom[i]+j)&255 for j in range(n));i+=1
  else:
   if cmd>=6:pos=len(out)-rom[i];i+=1
   else:pos=rom[i]|rom[i+1]<<8;i+=2
   for j in range(n):out.append(out[pos+j]^(255 if cmd&1 else 0))
def words(b):return [int.from_bytes(b[i:i+2],'little') for i in range(0,len(b),2)]
src=root/'Randomizer/upstream/patches/common/src'
font=dec(0x97e7de);original=words(dec(0x97eeff));pal=words(rom[pc(0x8ce9e9):pc(0x8ce9e9)+256])
# Original Zebes approach backdrop (Intro_Func86, BG1 mode 1).
tiles=dec(0x96ec76);maps=words(dec(0x978adb));planetpal=words(rom[pc(0x8ce5e9):pc(0x8ce5e9)+512])
planet=[]
for y in range(224):
 for x in range(256):
  id=maps[y//8*32+x//8];px=7-x%8 if id&16384 else x%8;py=7-y%8 if id&32768 else y%8
  off=(id&1023)*32+py*2;bit=7-px
  ci=sum(((tiles[off+(b//2)*16+b%2]>>bit)&1)<<b for b in range(4))
  planet.append(((id>>10)&7)*16+ci if ci else 0)
# Tables retain original color and two-row font geometry.
tables={}
for name in ['pink','purple','yellow','cyan','blue','green','orange','big']:
 tables[name]={m[2][0]:int(m[1],16) for l in (src/f'tables/{name}.tbl').read_text().splitlines() if (m:=re.match(r'([0-9a-fA-F]+)=(.+)',l))}
rows={};color='pink'
credittext=(src/'credits.asm').read_text()
for l in credittext.split('credits:\n',1)[1].split('warnpc',1)[0].splitlines():
 if (m:=re.match(r'\s*!(pink|purple|yellow|cyan|blue|green|orange|big)\s*$',l)):color=m[1]
 if (m:=re.match(r'\s*dw "([^"]*)"\s*;;\s*(\d+)',l)):
  rows[int(m[2])]=[tables[color].get(c,0x7f) for c in m[1].ljust(32)[:32]]
# Original VARIA display order, ending before seed parameters/statistics.
script=credittext.split('script:\n',1)[1].split('stats:\n',1)[0]
order=[]
for l in script.splitlines():
 if '!row*145' in l:break
 if (m:=re.search(r'dw !draw, !row\*(\d+)',l)):order.append(int(m[1]))
 elif 'dw !draw, !blank' in l:order.append(-1)
roll=[]
for r in order:roll.append([0x7f]*32 if r<0 else original[r*32:r*32+32] if r<128 else rows[r])
# Enough font data is present for the original 8x16 glyphs, not the post-credit VARIA item screen font.
out=['/* Original SM/VARIA assets; generated by Scripts/build-credits-assets.py. */']
def arr(name,ctype,values,width=0):
 out.append(f'static const {ctype} {name}'+(f'[][ {width} ]' if width else f'[{len(values)}]')+' = {')
 if width:out.extend('{'+','.join(map(str,v))+'},' for v in values)
 else:out.append(','.join(map(str,values)))
 out.append('};')
# Ship extraction instructions, never the original font/planet/credit tilemaps.
out += [f'static uint8_t credits_font[{len(font)}];',
        'static uint16_t credits_palette[128];',
        'static uint8_t credits_planet[256*224];',
        'static uint16_t credits_planet_palette[256];',
        f'static uint16_t credits_upstream[{len(roll)}][32];']
arr('credits_source_rows','int16_t',order)
custom = sorted(set(r for r in order if r >= 128))
arr('credits_varia_row_ids','uint16_t',custom)
arr('credits_varia_rows','uint16_t',[rows[r] for r in custom],32)
arr('credits_small_font','uint16_t',[tables['pink'].get(chr(c).upper(),0x7f)&1023 for c in range(128)])
arr('credits_big_font','uint16_t',[tables['big'].get(chr(c),0x7f) for c in range(128)])
(root/'Native/sm_credits_assets.inc').write_text('\n'.join(out)+'\n')
(root/'Docs/Credits/assets.json').write_text(json.dumps(dict(romSha1=hashlib.sha1(rom).hexdigest(),fontAddress='97:E7DE',fontBytes=len(font),planetTiles='96:EC76',planetMap='97:8ADB',upstreamCreditRows=len(roll),upstreamRevision=__import__('subprocess').check_output(['git','-C',str(root/'Randomizer/upstream'),'rev-parse','HEAD'],text=True).strip()),indent=2)+'\n')
if __name__=='__main__':print('Credits original assets:',len(font),'font bytes;',len(roll),'upstream rows')
