#!/usr/bin/env python3
"""Translate and byte-verify the pinned Mirror door-scroll routines."""
import hashlib,json,re,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'Randomizer/upstream'))
from rom.ips import IPS_Patch
source=root/'Randomizer/upstream/patches/mirror/src/include/bank_8f_area_door_scroll.asm'
rom=bytearray((root/'roms/Super Metroid (Japan, USA) (En,Ja).sfc').read_bytes())
patch=root/'Randomizer/upstream/patches/mirror/ips/bank_8f.ips'
for a,b in IPS_Patch.load(patch).toDict().items():rom[a:a+len(b)]=bytes(b)
programs=[];program=None;value=None;width8=False
for raw in source.read_text().splitlines():
 line=raw.split(';')[0].strip()
 if not line or line.startswith(('arch ','lorom','incsrc ','%','warnpc ')):continue
 if line.startswith('org '):
  program=dict(address=int(line.split('$')[1],16),writes=[],bytes=[]);programs.append(program)
  value=None;width8=False;continue
 assert program is not None,line
 op,*args=line.split();op=op.upper()
 if op in ['PHP','PLP','RTS']:
  program['bytes'].append(dict(PHP=0x08,PLP=0x28,RTS=0x60)[op]);continue
 arg=int(args[0].replace('#','').replace('$',''),16)
 if op=='SEP':
  assert arg==0x20;program['bytes'] += [0xe2,arg];width8=True
 elif op=='LDA':
  assert width8 and 0<=arg<=2;value=arg;program['bytes'] += [0xa9,arg]
 elif op=='STA':
  assert width8 and value is not None and 0x7ecd20<=arg<0x7ecd52
  program['writes'].append([arg-0x7ecd20,value]);program['bytes'] += [0x8f,arg&255,(arg>>8)&255,arg>>16]
 else:raise ValueError('Untranslated operation: '+line)
assert len(programs)==75 and len({p['address'] for p in programs})==75
for p in programs:
 pc=((p['address']>>16)&127)*32768+(p['address']&32767)
 assert rom[pc:pc+len(p['bytes'])]==bytes(p['bytes']),hex(p['address'])
canonical=json.dumps(programs,sort_keys=True,separators=(',',':')).encode();digest=hashlib.sha256(canonical).hexdigest()
lines=['/* Generated by build-mirror-scrolls.py; byte-verified source semantics. */',
 'static const char mirror_scroll_catalog[]="'+digest+'";',
 'static int mirror_scroll_write(uint32_t address){switch(address){']
for p in programs:
 lines.append('case 0x%x:'%p['address'])
 lines.extend('  scrolls[%d]=%d;'%tuple(w) for w in p['writes']);lines.append('  return 1;')
lines.append('default:return 0;}}')
(root/'Native/sm_mirror_scrolls.inc').write_text('\n'.join(lines)+'\n')
out=root/'Docs/Randomizer/FullOptions/Mirror';out.mkdir(parents=True,exist_ok=True)
(out/'scrolls.json').write_text(json.dumps(dict(sha256=digest,programs=programs,sourceSha256=hashlib.sha256(source.read_bytes()).hexdigest(),patchSha256=hashlib.sha256(patch.read_bytes()).hexdigest()),indent=2)+'\n')
print('MIRROR_SCROLL_SOURCE_PASS',len(programs),digest)
