#!/usr/bin/env python3
"""Lock Scavenger location IDs, HUD labels and source persistence identities."""
import hashlib,json,re,sys,runpy
from pathlib import Path
root=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(root/'Randomizer/upstream'))
from logic.logic import Logic
Logic.factory('vanilla')
asm=(root/'Randomizer/upstream/patches/common/src/varia_hud.asm').read_text()
labels=re.findall(r'dw "([^"]+)"',asm.split('scav_names:')[1].split(';; special values')[0])
assert len(labels)==18 and labels[-1]=='Hunt over '
locations=sorted((loc for loc in Logic.locations() if loc.HUD is not None),key=lambda l:l.HUD)
assert [loc.HUD for loc in locations]==list(range(17))
rows=[dict(name=l.Name,id=l.Id,hud=l.HUD,address=l.Address,boss=l.isBoss(),label=labels[l.HUD]) for l in locations]
assert rows[-1]['name']=='Ridley' and rows[-1]['id']==0xaa
catalog=dict(schema=1,abiSize=44,indexAddress=0xd8f4,startedEvent=147,completeEvent=129,
             huntOver=0xff11,terminator=0xffff,locations=rows,labels=labels,prompt='Press X-Y ')
catalog['sha256']=hashlib.sha256(json.dumps(catalog,sort_keys=True,separators=(',',':')).encode()).hexdigest()
p=root/'Randomizer/native_scavenger.json'
if p.exists():assert json.loads(p.read_text())==catalog,'Version Scavenger identities before changing them'
else:p.write_text(json.dumps(catalog,indent=2)+'\n')
lines=['/* Pinned VARIA Scavenger data; generated by build-scavenger.py. */',
       f'static const char scavenger_catalog[]="{catalog["sha256"]}";',
       'static const uint16_t scavenger_entries[17]={'+','.join(hex(r['id']<<8|r['hud']) for r in rows)+'};',
       'static const char *const scavenger_labels[18]={'+','.join(json.dumps(s) for s in labels)+'};']
(root/'Native/sm_scavenger.inc').write_text('\n'.join(lines)+'\n')
ui=['// Pinned source Scavenger identities. Generated by build-scavenger.py.',
    'static const TCHAR* NativeScavengerCatalog=TEXT("'+catalog['sha256']+'");',
    'static const struct {uint16 Word; const TCHAR* Name;} NativeScavengerSpecs[]={']
ui+=['{%d,TEXT(%s)},'%(row['id']<<8|row['hud'],json.dumps(row['name'])) for row in rows]
ui+=['};']
(root/'Unreal/Source/SMUnreal/SMNativeScavenger.inl').write_text('\n'.join(ui)+'\n')
patch=runpy.run_path(str(root/'Randomizer/upstream/patches/vanilla/patches.py'))['patches']['Blinking[RidleyRoomIn]']
assert patch=={0x78e98:[0x42,0xc8,0x0e,0x06,0x5a,0x8c],0x10a638:[0]}
door=['/* Original Ridley PLM and room-population data; no executable bytes. */',
      'static const struct {uint32_t address;uint8_t size,data[6];} scavenger_door[]={']
door+=['{%d,%d,{%s}},'%(addr,len(values),','.join(map(str,values))) for addr,values in patch.items()]
door+=['};','#define SCAVENGER_DOOR_BYTES 7']
(root/'Native/sm_scavenger_door.inc').write_text('\n'.join(door)+'\n')
out=root/'Docs/Randomizer/FullOptions/Scavenger';out.mkdir(exist_ok=True)
source_files=['Randomizer/upstream/patches/common/src/varia_hud.asm','Randomizer/upstream/rom/rompatcher.py',
              'Randomizer/upstream/graph/location.py','Randomizer/upstream/solver/commonSolver.py']
(out/'catalog.json').write_text(json.dumps(dict(catalog=catalog,ridleyDoorData=patch,sources={f:hashlib.sha256((root/f).read_bytes()).hexdigest() for f in source_files+['Randomizer/upstream/patches/vanilla/patches.py']}),indent=2)+'\n')
print('SCAVENGER_CATALOG',len(rows),catalog['sha256'])
