#!/usr/bin/env python3
"""Compile the pinned objective condition catalog for native evaluation."""
import hashlib,json,sys
from pathlib import Path
root=Path(__file__).resolve().parents[1];sys.path.insert(0,str(root/'Randomizer/upstream'))
from logic.logic import Logic
Logic.factory('vanilla')
from utils.objectives import Objectives
from graph.graph_utils import graphAreas
source=json.loads((root/'Docs/Randomizer/FullOptions/Objectives/events-audit.json').read_text());events=source['events']
kinds=['event','bosses','minibosses','nothing','item_percent','upgrades','area_clear','map_percent','area_explore','robots','animals','enemy_family']
direct=dict(kraid_is_dead='kraid',phantoon_is_dead='phantoon',draygon_is_dead='draygon',ridley_is_dead='ridley',spore_spawn_is_dead='spospo',botwoon_is_dead='botwoon',crocomire_is_dead='croc',golden_torizo_is_dead='GT',scavenger_hunt_completed='hunt_over',fish_tickled='fish_tickled',orange_geemer='orange_geemer',shak_dead='shak_dead',king_cac_dead='king_cac')
rows=[]
for i,(name,g) in enumerate(Objectives.goals.items()):
    symbol=g.symbol.removeprefix('objectives_');kind=None;arg=0
    if symbol in direct:kind='event';arg=events[direct[symbol]+'_event']
    elif symbol=='all_g4_dead':kind='bosses';arg=4
    elif symbol.startswith('boss_'):kind='bosses';arg=int(symbol.split('_')[1])
    elif symbol=='all_mini_bosses_dead':kind='minibosses';arg=4
    elif symbol.startswith('miniboss_'):kind='minibosses';arg=int(symbol.split('_')[1])
    elif symbol=='nothing_objective':kind='nothing'
    elif name.startswith('collect ') and '%' in name:kind='item_percent';arg=int(name.split()[1].rstrip('%'))
    elif symbol=='all_major_items':kind='upgrades'
    elif name.startswith('clear '):kind='area_clear';arg=graphAreas.index(g.area)
    elif name.startswith('explore ') and '%' in name:kind='map_percent';arg=int(name.split()[1].rstrip('%'))
    elif name.startswith('explore '):kind='area_explore';arg=graphAreas.index(g.area)
    elif symbol=='all_chozo_robots':kind='robots'
    elif symbol=='visited_animals':kind='animals'
    elif symbol.startswith('kill_all_'):kind='enemy_family';arg=['space_pirates','ki_hunters','beetoms','cacatacs','kagos','yapping_maws'].index(symbol.removeprefix('kill_all_'))
    assert kind is not None,name
    rows.append(dict(id=i,name=name,symbol=g.symbol,kind=kind,arg=arg,progress=g.inProgressSymbol,supported=name!='finish scavenger hunt'))
assert len(rows)==59
catalog=dict(schema=1,abiSize=272,eventCatalog=source['persistentCatalogSha256'],goals=rows)
catalog['sha256']=hashlib.sha256(json.dumps(catalog,sort_keys=True,separators=(',',':')).encode()).hexdigest()
path=root/'Randomizer/native_objectives.json'
if path.exists():assert json.loads(path.read_text())==catalog,'Version objective condition catalog before changing identities'
else:path.write_text(json.dumps(catalog,indent=2)+'\n')
locations=sorted(json.loads((root/'Randomizer/native_locations.json').read_text())['locations'],key=lambda p:p['address'])
byaddr={l.Address:l for l in Logic.locations() if not l.isBoss()}
regions=[graphAreas.index(byaddr[l['address']].GraphArea) for l in locations]
lines=['/* Source condition identities; generated by build-objectives.py. */','enum {'+','.join('OBJ_KIND_'+k.upper() for k in kinds)+'};',f'static const char objective_catalog[]="{catalog["sha256"]}";', 'static const struct {uint8_t kind;uint16_t arg;uint8_t supported;} objective_conditions[]={']
lines+=['{OBJ_KIND_%s,%d,%d},'%(r['kind'].upper(),r['arg'],r['supported']) for r in rows]
lines+=['};','static const uint8_t objective_location_regions[100]={'+','.join(map(str,regions))+'};','static const uint8_t objective_boss_events[4]={72,88,96,80};','static const uint8_t objective_miniboss_events[4]={73,97,81,82};','static const uint16_t objective_robot_events[4]={82,66,145,12};','static const uint16_t objective_family_events[6]={198,199,200,201,202,203};']
(root/'Native/sm_objectives.inc').write_text('\n'.join(lines)+'\n')
print('OBJECTIVE_CONDITIONS',len(rows),'goals',catalog['sha256'])

# The profile parser validates the exact same immutable IDs and full-layout totals.
ui=['/* Generated from the same pinned objective catalog as native C. */',f'static const TCHAR* NativeObjectiveCatalog=TEXT("{catalog["sha256"]}");',
    'static const struct {const TCHAR* Name; bool Supported;} NativeObjectiveSpecs[]={']
ui+=['{TEXT('+json.dumps(r['name'])+'),'+('true' if r['supported'] else 'false')+'},' for r in rows]
ui+=['};','static const uint16 NativeObjectiveMapTotals[2][12]={']
for layout in ['vanilla_layout','area_rando']:
    ui+=['{'+','.join(str(Logic.map_tilecount[layout][name] if i not in [0,11] else 0) for i,name in enumerate(graphAreas))+'},']
ui+=['};']
(root/'Unreal/Source/SMUnreal/SMNativeObjectives.inl').write_text('\n'.join(ui)+'\n')
